### PR TITLE
Update dependencies

### LINKED ISSUE #80: React 16 - Not working
Hi Team,
   can we have this library for React 16. I see it is using React.createElement and both React.createElement and React.PropTypes has been deprecated.

### PR DESCRIPTION
**Pull request by MDOR**
## Description
- Update dependencies
- Include setup for jest
- Remove mapCoverage option (is deprecated)

Closes #80 
Closes #87

### CODE REVIEW

**Comment by MDOR** [comment]
I'm still alive 😅 ! 

image
@AlgusDark  :D

**Comment by jonasgrunert** [comment]
Your build will fail due to the same error after jest version as [#87](https://github.com/AlgusDark/bloomer/pull/87). I would recommend merging my pull request and afterwards yours will compile.

**Comment by MDOR** [comment]
Not sure, dont get me wrong, I tested locally and is working as expected.
Is any way to run again Travis without push something?
It can be related to some issue with Travis

**Comment by AlgusDark** [comment]
yeah, it seems that Travis is complaining, I believe that @jonasgrunert fixed this with `--runInBand`.

Every new commit in your PR will trigger [Travis](https://travis-ci.org/AlgusDark/bloomer/builds/345136631?utm_source=github_status&utm_medium=notification)

**Comment by MDOR** [comment]
I didn't see the last commit, definitely we should merge the PR from @jonasgrunert first :D

**Comment by AlgusDark** [comment]
@mdor any chance we can sync with master?

Thanks.

**Pull request merged**
